openapi: 3.0.0
info:
  description: Yelp API
  version: 1.0.0
  title: Yelp API
paths:
  /businesses/search:
    get:
      operationId: getBusinesses
      summary: Get businesses
      description: Get businesses
      parameters:
        - name: term
          in: query
          required: false
          description: "Search term, e.g. 'food' or 'restaurants'. The term may also be the business's name, such as 'Starbucks'. If term is not included the endpoint will default to searching across businesses from a small number of popular categories."
          schema:
            type: string
        - name: location
          in: query
          required: false
          description: "Required if either latitude or longitude is not provided. This string indicates the geographic area to be used when searching for businesses. Examples: 'New York City', 'NYC', '350 5th Ave, New York, NY 10118'. Businesses returned in the response may not be strictly within the specified location."
          schema:
            type: string
        - name: latitude
          in: query
          required: false
          description: "Required, if location is not provided. Latitude of the location to search from. If latitude is provided, longitude is required too."
          schema:
            type: string
        - name: longitude
          in: query
          required: false
          description: "Required if location is not provided. Longitude of the location to search from. If longitude is provided, latitude is required too."
          schema:
            type: string
        - name: radius
          in: query
          required: false
          description: "A suggested search radius in meters. This field is used as a suggestion to the search. The actual search radius may be lower than the suggested radius in dense urban areas, and higher in regions of less business density. If the specified value is too large, a AREA_TOO_LARGE error may be returned. The max value is 40,000 meters (about 25 miles)."
          schema:
            type: integer
            maximum: 40000
        - name: categories
          in: query
          required: false
          description: "Categories to filter the search results with. See the list of supported categories. The category filter can be a list of comma delimited categories. e.g., 'bars,french' will filter by Bars OR French. The category alias should be used (e.g. 'discgolf', not 'Disc Golf')."
          schema:
            type: array
            items:
              type: string
        - name: locale
          in: query
          required: false
          description: "Locale code in the format of {language code}_{country code}. See the list of supported locales."
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: "Number of results to return."
          schema:
            type: integer
            maximum: 50
        - name: offset
          in: query
          required: false
          description: "Offset the list of returned results by this amount."
          schema:
            type: integer
        - name: sort_by
          in: query
          required: false
          description: "Suggestion to the search algorithm that the results be sorted by one of the these modes: best_match, rating, review_count or distance. The default is best_match. Note that specifying the sort_by is a suggestion (not strictly enforced) to Yelp's search, which considers multiple input parameters to return the most relevant results. e.g., the rating sort is not strictly sorted by the rating value, but by an adjusted rating value that takes into account the number of ratings, similar to a Bayesian average. This is to prevent skewing results to businesses with a single review."
          schema:
            type: string
            enum:
              - best_match
              - rating
              - review_count
              - distance
        - name: price
          in: query
          required: false
          style: form
          explode: false
          description: "Pricing levels to filter the search result with: 1 = $, 2 = $$, 3 = $$$, 4 = $$$$. The price filter can be a list of comma delimited pricing levels. e.g., '1, 2, 3' will filter the results to show the ones that are $, $$, or $$$."
          schema:
            type: array
            items:
              type: string
              enum:
                - 1
                - 2
                - 3
                - 4
        - name: open_now
          in: query
          required: false
          description: "When set to true, only return the businesses that are open now. Notice that open_at and open_now cannot be used together."
          schema:
            type: boolean
        - name: open_at
          in: query
          required: false
          description: "An integer representing the Unix time in the timezone of the search location. If specified, it will return businesses open at the given time. Notice that open_at and open_now cannot be used together."
          schema:
            type: integer
#            maximum: 2147483647
        - name: attributes
          in: query
          required: false
          style: form
          explode: false
          description: "Try these additional filters to return specific search results!
- hot_and_new - popular businesses which recently joined Yelp
- request_a_quote - businesses which actively reply to Request a Quote inquiries
- reservation - businesses with Yelp Reservations bookings enabled on their profile page
- waitlist_reservation - businesses with Yelp Wait List bookings enabled on their profile screen (iOS/Android)
- deals - businesses offering Yelp Deals on their profile page
- gender_neutral_restrooms - businesses which provide gender neutral restrooms
- open_to_all - businesses which are Open To All
- wheelchair_accessible - businesses which are Wheelchair Accessible
Premium Access Tier attributes:
- liked_by_vegetarians - businesses which are liked by vegetarians
- outdoor_seating - businesses with outdoor seating areas
- parking_garage - businesses which itself has a garage or there is a parking garage nearby
- parking_lot - businesses which have a parking lot
- parking_street - businesses with street parking available nearby
- parking_valet - businesses which offer a valet parking
- parking_validated - businesses which can validate a parking ticket from an external parking
- parking_bike - businesses with bike parking type
- restaurants_delivery - restaurants which offer delivery service
- restaurants_takeout - restaurants with take-out option
- wifi_free - businesses with free WiFi
- wifi_paid - businesses with paid WiFi
You can combine multiple attributes by providing a comma separated like 'attribute1,attribute2'.
  If multiple attributes are used, only businesses that satisfy all the attributes will be returned in search results.
  e.g., the attributes 'hot_and_new,request_a_quote' will return businesses that are 'Hot and New', and offer 'Request a Quote'."
          schema:
            type: array
            items:
              type: string
              enum:
                - hot_and_new
                - request_a_quote
                - reservation
                - waitlist_reservation
                - deals
                - gender_neutral_restrooms
                - open_to_all
                - wheelchair_accessible
      x-dependencies:
        - Or(location, latitude AND longitude);
        - ZeroOrOne(open_now, open_at);
        - offset + limit <= 1000;
        - IF offset AND NOT limit THEN offset <= 980;
      responses:
        "200":
          description: Returns all businesses
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BusinessesResult"
#        "400":
#          description: bad request
#  /transactions/{transaction_type}/search:
#    get:
#      operationId: getTransactions
#      summary: Get transactions
#      description: Get transactions
#      parameters:
#        - name: transaction_type
#          in: path
#          required: true
#          schema:
#            type: string
#        - name: location
#          in: query
#          required: false
#          description: "Required when latitude and longitude aren't provided. Address of the location you want to deliver to."
#          schema:
#            type: string
#        - name: latitude
#          in: query
#          required: false
#          description: "Required when latitude and longitude aren't provided. Address of the location you want to deliver to."
#          schema:
#            type: string
#        - name: longitude
#          in: query
#          required: false
#          description: "Required when location isn't provided. Longitude of the location you want to deliver to."
#          schema:
#            type: string
#      x-dependencies:
#        - Or(location, latitude AND longitude);
#      responses:
#        200:
#          description: Returns all businesses
#          content:
#            application/json:
#              schema:
#                $ref: '#/definitions/BusinessesResult'
#        400:
#          description: bad request
servers:
  - url: https://api.yelp.com/v3
components:
  schemas:
    BusinessesResult:
      type: object
      properties:
        total:
          type: integer
          description: "Total number of businesses Yelp finds based on the search criteria. Sometimes, the value may exceed 1000. In such case, you still can only get up to 1000 businesses using multiple queries and combinations of the 'limit' and 'offset' parameters."
        region:
          type: object
          description: "Suggested area in a map to display results in."
          properties:
            center:
              type: object
              properties:
                latitude:
                  description: "Latitude position on map."
                  type: number
                longitude:
                  description: "Longitude position on map."
                  type: number
        businesses:
          type: array
          items:
            type: object
            properties:
              categories:
                type: array
                description: "List of category title and alias pairs associated with this business."
                items:
                  type: object
                  properties:
                    alias:
                      type: string
                      description: "Alias of a category, when searching for business in certain categories, use alias rather than the title."
                    title:
                      type: string
                      description: "Title of a category for display purpose."
              coordinates:
                type: object
                description: "Coordinates of this business."
                properties:
                  latitude:
                    type: number
                    description: "Latitude position on map."
                  longitude:
                    type: number
                    description: "Longitude position on map."
              display_phone:
                type: string
                description: "Phone number of the business formatted nicely to be displayed to users. The format is the standard phone number format for the business's country."
              distance:
                type: number
                description: "Distance in meters from the search location. This value is in meters(m) regardless of the locale."
              id:
                type: string
                description: "Yelp Encrypted Business ID."
              alias:
                type: string
                description: "Unique Yelp alias of this business. Can contain unicode characters. Example: 'yelp-san-francisco'. Also see What's the difference between the Yelp business ID and business alias?"
              image_url:
                type: string
                description: "URL of photo for this business"
              is_closed:
                type: boolean
                description: "Whether business has been (permanently) closed"
              name:
                type: string
                description: "Name of this business."
              phone:
                type: string
                description: "Phone number of the business."
              price:
                type: string
                description: "Price level of the business. Value is one of $, $$, $$$ and $$$$."
                enum:
                  - $
                  - $$
                  - $$$
                  - $$$$
                  - £
                  - ££
                  - £££
                  - ££££
                  - €
                  - €€
                  - €€€
                  - €€€€
                  - ￥
                  - ￥￥
                  - ￥￥￥
                  - ￥￥￥￥
              rating:
                type: number
                description: "Rating for this business (value ranges from 1, 1.5, ... 4.5, 5)."
                minimum: 1
                maximum: 5
              review_count:
                type: integer
                description: "Number of reviews for this business."
              url:
                type: string
                description: "URL for business page on Yelp."
              transactions:
                type: array
                description: "List of Yelp transactions that the business is registered for. Current supported values are pickup, delivery and restaurant_reservation."
                items:
                  type: string
                  enum:
                    - pickup
                    - delivery
                    - restaurant_reservation
              location:
                type: object
                description: "Location of this business, including address, city, state, zip code and country."
                properties:
                  address1:
                    type: string
                    nullable: true
                    description: "Street address of this business."
                  address2:
                    type: string
                    nullable: true
                    description: "Street address of this business, continued."
                  address3:
                    type: string
                    nullable: true
                    description: "Street address of this business, continued."
                  city:
                    type: string
                    description: "City of this business."
                  country:
                    type: string
                    description: "ISO 3166-1 alpha-2 country code of this business."
                  display_address:
                    type: array
                    description: "Array of strings that if organized vertically give an address that is in the standard address format for the business's country."
                    items:
                      type: string
                  state:
                    type: string
                    description: "ISO 3166-2 (with a few exceptions) state code of this business."
                  zip_code:
                    type: string
                    description: "Zip code of this business."